### ISSUE TITLE
Question about Baryonic Feedback

### ISSUE THREAD

**Issue by Saber-of-QFT** [alexander-mead/pyhalomodel#1]
Dear Mead,
         Hello, I notice that, in this version of your code, I can't find any parameters which relate to baryonic feedback (for example, T_AGN, or A & eta). I try to find out if you have new treatment for baryonic feedback, but the link of your review paper ([Asgari, Mead & Heymans (2023)](https://arxiv.org/)) seen to be failed. So I decide to ask it here.

Thank you！

**Comment by alexander-mead** [comment]
Hi,

Thanks for your interest. I'm amazed that you found this repository, the reason that the link failed is that the paper has not been put on arXiv yet... it should be out in a couple of weeks.

Note that this repository implements a pure vanilla halo model calculation, rather than the augmented `HMcode` recipe. So there are none of those parameters that you mention. Although keep in mind that using this code you could put any halo profile you choose through the halo model, so you could investigate feedback that way.

I think you might be interested in this `Python` version of [`HMcode`](https://github.com/alexander-mead/pyhmcode), which uses the code in this repository. However, that doesn't have the feedback model in it yet. This would be quite quick to add though...

I'm also still actively developing these repositories, so there will be many changes between now and the end of the month (February) which is my deadline for having them finished.

Cheers,
Alexander

**Comment by Saber-of-QFT** [comment]
Hi,

It is good to know that you still working on developing the python version. HMCode is not only a useful tool in cosmological research, but also a good demonstrate for studying the theroy of halo model. And a pure python version is very convenience, especially for people who suck at Fortran (me, for example ...)

I didn't realize that your have left academia untill I read your statement in https://github.com/alexander-mead/pyhmcode. I think it is such a noble act, that you still willing to make contribution to astrophysics after you leaving this field. And I am looking forward to witness the completion of the pyhmcode.

Thank you very much, and wish you have a great adventrue in the field of data science!

Cheers!

**Comment by alexander-mead** [comment]
Hi,

Thanks for your kind words! It's not that selfless though, I'm still an astronomer until Tuesday, and am being paid as such, so I've got two more days to work on these repositories.

I guess I'll hope to keep them maintained though, so maybe that will be a selfless act...

Cheers,
Alexander
